apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.argocd.HTTPRoute.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argocd.HTTPRoute.syncWaves | quote }} 
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}          
      namespace: {{ .Values.gateway.namespace }} 
  hostnames:
    - {{ .Values.argocd.HTTPRoute.hostName }}           
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.argocd.HTTPRoute.path }}      
      backendRefs:
        - group: ''	
          kind: Service
          name: {{ .Values.argocd.HTTPRoute.serviceName }} 
          port: {{ .Values.argocd.HTTPRoute.port }}
          weight: 1

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
    argocd.argoproj.io/tracking-id: app-dev:gateway.networking.k8s.io/HTTPRoute:dev/app-route
  name: app-route-2
  namespace: dev
spec:
  hostnames:
    - dev.example.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
      namespace: gateway
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: frontend
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /