apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    aws:
      service: {{ .Values.secretStore.provider.service }}
      region: {{ .Values.secretStore.provider.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStore.serviceAccount.name }}
            namespace: {{ .Values.secretStore.serviceAccount.namespace }}
            
