apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: {{ .Values.secretStore.provider.service }}
      region: {{ .Values.secretStore.provider.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
            namespace: {{ .Values.namespace }}
