apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.gatewayClass.syncWaves | quote }}
spec:
  controllerName: {{ .Values.gatewayClass.controllerName }}